-- 
USE ROLE SECURITYADMIN;

-- Create the role for dbt
CREATE ROLE IF NOT EXISTS TRANSFORMER;
GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORMER;

-- Create the dbt User
CREATE USER IF NOT EXISTS dbtUser
    PASSWORD = 'dbtUserPass123@'
    LOGIN_NAME = 'dbtUser'
    MUST_CHANGE_PASSWORD = TRUE
    DEFAULT_WAREHOUSE='COMPUTE_WH'
    DEFAULT_ROLE=TRANSFORMER;

-- Grant role to user
GRANT ROLE TRANSFORMER TO USER dbtUser;

-- Grant necessary privileges to role
USE ROLE SYSADMIN;

GRANT ALL ON DATABASE dbt_dbtFundamentals_RAW TO ROLE TRANSFORMER;
GRANT ALL ON ALL SCHEMAS IN DATABASE dbt_dbtFundamentals_RAW TO ROLE TRANSFORMER;
GRANT ALL ON ALL TABLES IN DATABASE dbt_dbtFundamentals_RAW TO ROLE TRANSFORMER;

GRANT ALL ON DATABASE dbt_dbtFundamentals_DW TO ROLE TRANSFORMER;
GRANT ALL ON ALL SCHEMAS IN DATABASE dbt_dbtFundamentals_DW TO ROLE TRANSFORMER;
GRANT ALL ON ALL TABLES IN DATABASE dbt_dbtFundamentals_DW TO ROLE TRANSFORMER;

USE ROLE ACCOUNTADMIN;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE dbt_dbtFundamentals_RAW TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN DATABASE dbt_dbtFundamentals_RAW TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE dbt_dbtFundamentals_DW TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN DATABASE dbt_dbtFundamentals_DW TO ROLE TRANSFORMER;


