WITH cte_RAW_REVIEWS AS (
    SELECT  
        *
    FROM    
        {{ source('airbnb', 'RAW_REVIEWS') }}
)

SELECT  
    LISTING_ID,
    "DATE" AS REVIEW_DATE,
    REVIEWER_NAME,
    COMMENTS AS REVIEW_TEXT,
    SENTIMENT AS REVIEW_SENTIMENT
FROM    
    cte_RAW_REVIEWS