version: 2

sources:
  - name: airbnb
    database: DBT_AIRBNB_RAW  
    schema: PUBLIC  
    tables:
      - name: RAW_LISTINGS
      - name: RAW_HOSTS
      - name: RAW_REVIEWS
        #loaded_at_field: date
        #freshness:
          #warn_after: {count: 12, period: hour}
          #error_after: {count: 24, period: hour}