[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "ca_dagster_dbt_fundamentals.definitions"
code_location_name = "ca_dagster_dbt_fundamentals"